### ISSUE TITLE
loaddivisions should be idempotent

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/python-opencivicdata-django#12]

**Comment by paultag** [comment]
I think it's able to load in a safer way now, I think this is mostly safe to run multiple times regardless of state - cool to close, @jamesturk ?

**Comment by mileswwatkins** [comment]
@paultag, is this good to close?

**Comment by mileswwatkins** [comment]
I think the issue remaining here is that if the number of divisions stays the same but the divisions themselves change then they don't get reloaded. An edge case to be sure, but not out of the question.

**Comment by mileswwatkins** [comment]
This PR should solve the problem.
