### ISSUE TITLE
Bill action classifcations

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/python-opencivicdata-django#19]
Here are some actions I'm not sure how to classify:

'Direct Introduction' seems to refer to legislation that was directly introduced to committe. I.e. not referred from the council to the committee.

'Remove Co-Sponsor(s)' https://chicago.legistar.com/LegislationDetail.aspx?ID=2073840&GUID=CB56231A-805A-4E3C-95D1-43EBD935959B

'Held in Committee'

'Deferred and Published'

**Comment by rshorey** [comment]
@fgregg, some thoughts and questions.

*Wanted to make sure you're aware that it's OK to have an action with no classification. We think this the best course of action for Remove Co-Sponsors. This is a thing that happens in a lot of legislatures, but they often don't say they're doing it (the sponsor would just disappear), so we think that having the information available as a classification could introduce confusion in cases where it happens but we can't capture it. So just add the action with no classification at this point.

*For Direct Introduction: I'd just use "Introduced" and add that committee as a related entity.

*For Held in Committee and Deferred: we're thinking we should add a status of Deferred. Do you have a sense of what exactly happens to a bill when one of these things happen? In both cases, does it just mean "not today, maybe later, but maybe never"? If so, I think we can call them both deferred, and just add the relevant committee as a related_entity where applicable.
