### ISSUE TITLE
What do the different amendment actions mean?

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/python-opencivicdata-django#20]
```
('amendment-introduction', 'Amendment Passage'),
('amendment-passage', 'Amendment Passage'),
('amendment-withdrawal', 'Amendment Withdrawal'),
('amendment-failure', 'Amendment Failure'),
('amendment-amended', 'Amendment Amended'),
```
Would any of these be appropriate for 'Amended in Committee'? https://chicago.legistar.com/LegislationDetail.aspx?ID=1990715&GUID=F7B80D9B-99C4-4E62-91C5-EE5B977167B1

**Comment by jamesturk** [comment]
amendment-passage would work- and that's a copy & paste bug in the display for amendment-introduction

**Comment by fgregg** [comment]
Thanks.
