### ISSUE TITLE
Explain why we had to avoid bulk insert + django + transaction

### ISSUE THREAD

**Issue by paultag** [opencivicdata/python-opencivicdata-django#28]
https://github.com/opencivicdata/python-opencivicdata-django/commit/2b86baeda9914bf682728c83dd169099628d6c11

Something about the pseduo-upsert we did made Django sad. We shoud be able to explain this, and eventually file a bug / fix with Django.

**Comment by paultag** [comment]
This is a pretty awesome heisenbug; if someone wants something to dig into, this is a fun one.

**Comment by jamesturk** [comment]
anyone know best way to reproduce this?  I'd like to check if it is still happening in Django 1.9

**Comment by jamesturk** [comment]
@paultag do you remember how to reproduce this?

**Comment by jpmckinney** [comment]
@jamesturk Shall we optimistically try reverting that commit?

**Comment by jamesturk** [comment]
Yeah, glad to give it a try soon but if you wind up in there feel free to
go for it.
