### ISSUE TITLE
Make Amendment Model

### ISSUE THREAD

**Issue by handlers** [opencivicdata/python-opencivicdata-django#30]
Just talked this over with @paultag — am I correct that there is no model for amendments? If there is none, how can we help get one started?

**Comment by paultag** [comment]
You appear to be correct; I have no idea how we lasted this long without one

**Comment by jpmckinney** [comment]
I may have some ideas about modeling. Happy to comment on any draft model.

**Comment by paultag** [comment]
:+1:, thanks James!

On Mon, Mar 30, 2015 at 3:24 PM, James McKinney <notifications@github.com>
wrote:

> I may have some ideas about modeling. Happy to comment on any draft model.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/python-opencivicdata-django/issues/30#issuecomment-87799026>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by fgregg** [comment]
What is the difference between amendments and versions of a bill?

**Comment by jpmckinney** [comment]
I think an amendment would be more structured, whereas a version has very little metadata.

**Comment by jamesturk** [comment]
if we need this it should be a new OCDEP, let's keep discussion of enhancements here: https://github.com/opencivicdata/docs.opencivicdata.org/issues/56
