### ISSUE TITLE
Generate reports

### ISSUE THREAD

**Issue by mileswwatkins** [opencivicdata/python-opencivicdata-django#36]
- Reports
  - [x] People: percentage missing [address, email, any telephone](http://www.popoloproject.com/specs/contact-detail.html#code-lists), photo
  - [x] Organizations: count by `classification` in `Jurisdiction`, total count empty
  - [ ] Posts: counts for vacancies and overages
  - [x] Bills: counts for no actions, no sponsors, no versions, duplicate versions, percentage actions without types, without sponsor IDs
  - [x] Votes: percentage bad counts
  - [ ] Events: (Would `Disclosure` checks go in here?)
- [x] Sorting
- [ ] Filters: by `Jurisdiction`, by number of "bad" cells
- [x] Thresholds and color-coding, integer and percent formatting

**Comment by mileswwatkins** [comment]
I'm going to wait on `Posts.over` until the discussion on `num_seats` is finished:
https://github.com/opencivicdata/pupa/pull/167

**Comment by jamesturk** [comment]
@mileswwatkins this is actually in pupa right?

**Comment by mileswwatkins** [comment]
Oh, good call, never realized the discrepancy. https://github.com/opencivicdata/pupa/pull/177

**Comment by mileswwatkins** [comment]
Moving.
