### ISSUE TITLE
Vote "requires" attribute

### ISSUE THREAD

**Issue by crdunwel** [opencivicdata/python-opencivicdata-django#38]
Different kinds of votes in different legislatures require different percentages of support to pass. Seems like important information to store about a vote - more important than shoving it into extra attributes. The `@opencongress` [congress scrapers include this attribute in votes](https://github.com/unitedstates/congress/wiki/votes) as you can see in the following example.

```
{
  "requires": "1/2", 
  "result": "Failed", 
  "result_text": "Failed"
}
```

The `result_text` may also be relevant too since we're storing passing as a boolean value instead of the actual text specific to the vote type. This may make more sense though to push to extra attributes.

**Comment by jamesturk** [comment]
to https://github.com/opencivicdata/docs.opencivicdata.org/issues/55 for discussion
