### ISSUE TITLE
Person/Organization image field source/note

### ISSUE THREAD

**Issue by crdunwel** [opencivicdata/python-opencivicdata-django#41]
The image field on Person and Organization models are only for a URL string. It seems metadata attributing credit or name of the source for the photo (GPO Member Guide) and a possible note (e.g. "Official Congress Headshot") would provide more complete information about the photo.

**Comment by jamesturk** [comment]
moving to https://github.com/opencivicdata/docs.opencivicdata.org/issues/54 for discussion as part of a future OCDEP
