### ISSUE TITLE
Proposal: 0.7.x branch

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/python-opencivicdata-django#53]
With the blessing of relevant parties I'd like to start work on an 0.7.x branch (and release a new 0.6.4 as necessary)

I'd propose the following:
- breaking backwards compatibility to fix the JSONField issue (#9, #31)
- dropping djorm-pgarray, jsonfield, and django-uuid in favor of django.contrib.postgres fields added in 1.8 and 1.9
- as 0.7.x will be 'pre-release' it will depend on Django 1.9 to avoid having to do this again when 1.9 drops
- I will work on postgres full text search on this branch, hopefully using Django 1.9's built in

Sunlight & anyone else running an instance could pin their systems to use 0.6.x for the time being, but 0.7.x would represent the future w/ working JSONfield & fewer deprecated dependencies on things like djorm-pgarray.  Once it has stable models a migration script could be written (likely outside the migration framework for practical reasons)

**Comment by jamesturk** [comment]
lots of the work for this is already here: 

https://github.com/jamesturk/python-opencivicdata-django/tree/cleanmodels

**Comment by boblannon** [comment]
:+1:

**Comment by fgregg** [comment]
This sounds good to me.

**Comment by jpmckinney** [comment]
:+1:
