### ISSUE TITLE
Why not make these models abstract=True?

### ISSUE THREAD

**Issue by palewire** [opencivicdata/python-opencivicdata-django#68]
I love the idea of this library, but I'm curious to know why the models aren't configured with ``abstract=True`` in their ``Meta`` settings. Am I correct to  assume that without that setting, the base models are now all created as tables in the database by Django? If I'm off in left field please just let me know and I will slink back in my cave.

**Comment by fgregg** [comment]
I think I don't fully understand your question. What pattern would you prefer? Who should be responsible for creating the tables?

**Comment by palewire** [comment]
I'll try to expand the point I'm making (or missing) in a test repository. Along the way, I think I might have found an itty bitty bug [here](https://github.com/opencivicdata/python-opencivicdata-django/pull/69).

**Comment by jamesturk** [comment]
@palewire did you ever wind up doing that test repo?  I think we're settled on these as non-abstract but definitely open to hearing cases we aren't covering well

**Comment by palewire** [comment]
I did but I think @gordonje has made things work as they as so I don't know if we need to add another requirement to getting things out. You should feel free to ignore me.

To me, the case for abstract is mostly database pendantry. My preference generally would be to have subclassed tables "stand alone" as a single table in the hard database behind Django, rather than two linked tables.
