### ISSUE TITLE
should we split this package into multiple apps?

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/python-opencivicdata-django#83]
First, to be clear- it could still be one repository (or not.. depending on what we decide)

That said, it might make sense to separate this out into multiple django apps, I'm thinking something like:

core.models -> People, Organization, etc. (essentially popolo & support models)
legislative.models -> Bill, VoteEvent, etc.
campaign_finance.models -> PR #81 
elections.models -> PR #82 

I know this came up briefly before but I feel like looking at the potential scope of the new models we should discuss this

**Comment by fgregg** [comment]
Could you articulate the perceived pros and cons?

**Comment by jamesturk** [comment]
Sure thing.

Pros of splitting:
- possible to only install the class of models that you want (I believe w/
auxillary models we're already at 60+ in what would become core &
legislative)
- better organized in Django Admin (grouped by app name)
- if we want to (either now or later) split into multiple repos it would be
possible.  this would have other benefits, such as easier to have multiple
maintainers

Cons of splitting (someone else might want to add to this):
- possible increase in complexity (what is in core app, etc?)
- more things to add to INSTALLED_APPS if you are indeed using all of them
- depending on how we do it, it might require people making the upgrade to
run a one-time script to rename their tables

**Comment by gordonje** [comment]
This seems like it would better fit use cases of the CCDC, which doesn't touch any of the legislative models. Not sure I'm thinking carefully enough about the cons, though.

It might help to think this through further by mapping out the dependencies between these separate apps. So:

* core has no dependencies.
* elections relies on core.
* campaign finance relies on elections (and also core).
* ???

**Comment by jamesturk** [comment]
If we do want to I think the questions to answer would be:

One repo or many?

- my vote is for one, I think dependencies will be easier that way, in fact i'm sort of regretting/reconsidering the python-opencivicdata-divisions split)

Should underlying table names all be set to 'opencivicdata_modelname' or should they become something like 'core_jurisdiction', 'core_person', 'legislative_bill'

- the latter is how Django would name them if we don't specify table names, so if we prefer to keep them as they are we'd need to manually set them on each model now & going forward
- changing them would require a script to be present for people to migrate from existing names to new ones, Django's normal migrations couldn't handle this case since it is cross-app

**Comment by gordonje** [comment]
Don't have strong feelings about one vs many repos. Though, wondering what implication that has for having multiple maintainers.

For the second q: Seems better for the db tables to include the prefix "opencivicdata_", as I suspect many django projects already have a "core" app, and figuring out which tables go with which app could be annoying/confusing. And it doesn't require the migration for current opencivicdata_django users

Manually setting the db tables on the Django models doesn't seem that awful to me. You could even have a CI test that checks to ensure contributors remember to do this.

**Comment by gordonje** [comment]
Actually, it's not all that obvious to me why one repo would be preferable, especially if we're talking about dividing up maintainer responsibilities. @jamesturk what are the regrets about splitting divisions off from opencivicdata_django?

**Comment by jamesturk** [comment]
- I'm with you on the tables not changing, it seems unnecessary & you're right that it could introduce other issues.
- one repo makes releases easier since there won't be the need for synchronized releases, avoids the namespace problem (making Py2 compatibility easier for those that need it for now), makes things like PRs/issues simpler since they can be to one repo instead of possibly having interdependencies (which has happened quite a few times)

As for split ownership, I think it'd make sense to give commit access to maintainers of any particular subset, and just ask that they're extra careful to not merge anything that affects core/common module without consultation w/ the rest of the maintainers.  I think in practice that won't be any harder than trying to coordinate across 3-4 repos

**Comment by jamesturk** [comment]
PR #85 addresses this

(also, since I merged in the work that moves py-ocd-divisions into this repo, things are Py 2.7 compatible again on master, keeping this as one repo will keep that possible as long as y'all need)
