### ISSUE TITLE
find replacement for django-jsonfield

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/python-opencivicdata-django#9]
if we want Postgres' JSON we may want to move away, this is a known issue.  https://github.com/bradjasper/django-jsonfield/issues/80

for now I've pinned the jsonfield version to 0.9.20 which doesn't have a problem, but we're getting weird errors on 0.9.22 (on travis) where the JSONField comes back as '{}' instead of {}

**Comment by paultag** [comment]
Yeah, I'm thinking jsonb is the way to go here; let's break out once we can land 9.4 and have a solid route to use it. 

Also, wow, this was the bug we were seeing not to long ago, cc @boblannon

**Comment by jamesturk** [comment]
closing this as Django 1.9 fixes this in 0.7
